# pyproject.toml
[project]
name = "bio"
version = "0.0.1"
authors = [
  { name="Lele", email="maggiori.samuele@gmail.com" },
]
description = "My personal workspace"
readme = "README.md"
requires-python = "==3.11"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[scripts]
cacca_train = "bio.cacca_train:main"
cacca_generate = "bio.cacca_generate:main"
psmile_train = "bio.psmile_train:main"
psmile_generate = "bio.psmile_generate:main"
combined_train = "bio.combined_train:main"
combined_generate = "bio.combined_generate:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["bio*"]

[tool.pytest.ini_options]
python_files = "*.py"
testpaths = ["bio"]
norecursedirs = [
  "__pycache__",
  ".cache_dir",
  ".pytest_cache",
  ".git",
  ".zed",
  ".vscode",
  "__HELPER_DIR__",
]
filterwarnings = [
    "ignore:'audioop' is deprecated:DeprecationWarning",
    "ignore:invalid escape sequence:DeprecationWarning",
    "ignore:.*GraphNetwork:DeprecationWarning",
    "ignore:.*SelfAttention Layer:DeprecationWarning",
    "ignore:.*pyparsing.*:DeprecationWarning",
    "ignore:.*NumPy global RNG.*:FutureWarning",
    "ignore::pyparsing.PyparsingDeprecationWarning",
    # "ignore:.*oneOf.*:PyparsingDeprecationWarning",
    # "ignore:.*parseString.*:PyparsingDeprecationWarning",
    # "ignore:.*resetCache.*:PyparsingDeprecationWarning",
    # "ignore:.*enablePackrat.*:PyparsingDeprecationWarning",
]
markers = [
    "verbose: tests that have some kind of output",
    "todo: test yet to implement",
    "above10s: test that require more than 10 seconds",
    "unreliable: test that depends on external factors, in the future it will fail",
    "infinite: test will not finish",
]
addopts = "-m 'not verbose and not todo and not above10s and not unreliable and not infinite'"
