[workspace]
authors = ["Lele <maggiori.samuele@gmail.com>"]
channels = ["conda-forge", "anaconda"]
name = "mytblite"
platforms = ["win-64", "linux-64"]
version = "0.0.1"
description = "Library for BIOLOGY development"

[dependencies]
python = "3.11.*"
tblite-python = "0.5.*"
ase = "*"

[pypi-dependencies]
new-import-system = { git = "https://github.com/Uomocosa/new-python-import-system" }
lele = { git = "https://github.com/Uomocosa/lele-py" }
pytest = "*"
loguru = "*"
tyro = "*"
# mytblite = { path = ".", editable = true } # <-- Add this line

[tool.setuptools]
packages = { find = { where = ["."], include = [
    "mytblite*",
] } }

[tool.pytest.ini_options]
python_files = "*.py"
testpaths = ["mytblite"]
norecursedirs = [
  "__pycache__",
  ".pytest_cache",
  ".git",
  ".zed",
  ".vscode",
  "__HELPER_DIR__",
]
filterwarnings = [
    "ignore:'audioop' is deprecated:DeprecationWarning",
    "ignore:invalid escape sequence:DeprecationWarning",
    "ignore:.*GraphNetwork:DeprecationWarning",
    "ignore:.*SelfAttention Layer:DeprecationWarning",
]
markers = [
    "verbose: tests that have some kind of output",
    "todo: test yet to implement",
    "above10s: test that require more than 10 seconds",
    "unreliable: test that depends on external factors, in the future it will fail",
    "infinite: test will not finish",
]
addopts = "-m 'not verbose and not todo and not above10s and not unreliable and not infinite'"
