import pandas as pd
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import AgglomerativeClustering
from bio.ML import AHC

def cluster(model: AHC):
    """
    Applies dimensionality reduction and clustering to a highly-featurized DataFrame.
    """
    df, options = model.df, model.options
    assert options.pca_components >= 2
    # 1. Isolate the numerical features generated by your featurize() function
    # This automatically ignores text columns like SOURCE, SMILES strings, etc.
    X_raw = df.select_dtypes(include=['float64', 'int64', 'float32', 'int32'])
    X_raw = X_raw.dropna()
    
    original_features = X_raw.columns
    
    # 2. Drop "Dead" Features (Features with zero variance across all rows)
    selector = VarianceThreshold(options.variance_threshold)
    X_filtered = selector.fit_transform(X_raw)
    print(f"Features reduced from {X_raw.shape[1]} to {X_filtered.shape[1]} after variance thresholding.")
    retained_features = original_features[selector.get_support()]
    model.pca_feature_names = retained_features
    
    # 3. Standardize the features
    # (Crucial because continuous features like Molecular Weight and binary Fingerprints have different scales)
    if options.scaler:
        X_scaled = options.scaler.fit_transform(X_filtered)
    else:
        X_scaled = X_filtered
   
    # 4. Apply PCA to reduce dimensions 
    # We compress the hundreds of remaining features into 15 dense Principal Components
    pca = PCA(n_components=options.pca_components, random_state=options.seed)
    X_pca = pca.fit_transform(X_scaled)
    model.pca_object = pca
    
    # 5. Apply Agglomerative Hierarchical Clustering
    # 'ward' linkage minimizes the variance of the clusters being merged
    clustering_model = AgglomerativeClustering(
        n_clusters=options.n_clusters, 
        metric=options.metric, 
        linkage=options.linkage
    )
    cluster_labels = clustering_model.fit_predict(X_pca)
    
    # 6. Append the cluster labels back to the original DataFrame
    df['Cluster'] = cluster_labels
    df['PCA_1'] = X_pca[:, 0]
    df['PCA_2'] = X_pca[:, 1]
    model.df = df


import pytest
@pytest.mark.todo
def test_():
    pass
