import pandas as pd
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import AgglomerativeClustering
import bio
from bio.ML import AHC
from loguru import logger

def cluster(df: pd.DataFrame, options: AHC.Options) -> AHC:
    """
    Applies dimensionality reduction and clustering to a highly-featurized DataFrame.
    """
    assert options.pca_components >= 2
    # 1. Isolate the numerical features generated by your featurize() function
    # This automatically ignores text columns like SOURCE, SMILES strings, etc.
    X_raw = df.select_dtypes(include=['float64', 'int64', 'float32', 'int32'])
    X_raw = X_raw.dropna()
    
    original_features = X_raw.columns
    
    # 2. Drop "Dead" Features (Features with zero variance across all rows)
    selector = VarianceThreshold(options.variance_threshold)
    X_filtered = selector.fit_transform(X_raw)
    logger.info(f"Features reduced from {X_raw.shape[1]} to {X_filtered.shape[1]} after variance thresholding.")
    retained_features = original_features[selector.get_support()]
    logger.info(f"Retained {len(retained_features)} features after variance thresholding.")
    logger.debug(f"retained_features:\n{retained_features}")
    model = AHC(
        df = df, 
        options = options, 
        pca_feature_names = retained_features
    )
    
    # 3. Standardize the features
    # (Crucial because continuous features like Molecular Weight and binary Fingerprints have different scales)
    if options.scaler:
        X_scaled = options.scaler.fit_transform(X_filtered)
    else:
        X_scaled = X_filtered
   
    # 4. Apply PCA to reduce dimensions 
    # We compress the hundreds of remaining features into N dense Principal Components
    max_components = min(X_scaled.shape[0], X_scaled.shape[1])
    if options.pca_components > max_components:
        error_msg = (
            f"Cannot calculate {options.pca_components} PCA components. "
            f"Dataset only has {X_scaled.shape[0]} rows and {X_scaled.shape[1]} features "
            f"(Max possible components: {max_components})."
        )
        logger.error(error_msg)
        raise ValueError(error_msg)

    pca = PCA(n_components=options.pca_components, random_state=options.seed)
    X_pca = pca.fit_transform(X_scaled)
    model.X_pca = X_pca
    model.pca_object = pca
    
    # 5. Apply Agglomerative Hierarchical Clustering
    # 'ward' linkage minimizes the variance of the clusters being merged
    clustering_model = AgglomerativeClustering(
        n_clusters=options.n_clusters, 
        metric=options.metric, 
        linkage=options.linkage
    )
    cluster_labels = clustering_model.fit_predict(X_pca)
    
    # 6. Append the cluster labels back to the original DataFrame
    df['CLUSTER'] = cluster_labels
    df['PCA_1'] = X_pca[:, 0]
    df['PCA_2'] = X_pca[:, 1]
    model.df = df
    return model


def test_():
    import pandas as pd
    from sklearn.preprocessing import StandardScaler
    from bio.__global__ import PDCC_CSV
    from bio.Dataset import PDCCMethod
    bio.setup_loguru()
    model_options = AHC.Options(
        n_clusters=5, 
        pca_components=10, 
        scaler=StandardScaler(),
    )
    featurizer_options = PDCCMethod.featurize.Options(
        capping_atoms = ['H'],
        molecule_features_to_calculate = ['logp', 'logd'],
        polymer_features_to_calculate = [],
    )
    df = pd.read_csv(PDCC_CSV)
    df = df.head(10)
    df = PDCCMethod.increment_dataset(df)
    df = PDCCMethod.convert_names_to_smiles(df)
    df = PDCCMethod.featurize(df, options=featurizer_options)
    ahc = cluster(df, model_options)
